# Generated by Django 5.2.5 on 2025-10-10 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideoShort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youtube_url', models.URLField(max_length=500)),
                ('original_title', models.CharField(max_length=500)),
                ('start_time', models.CharField(max_length=20)),
                ('end_time', models.CharField(max_length=20)),
                ('video_file', models.FileField(blank=True, null=True, upload_to='shorts/')),
                ('generated_title', models.CharField(blank=True, max_length=200)),
                ('generated_hashtags', models.TextField(blank=True)),
                ('uploaded_to_youtube', models.BooleanField(default=False)),
                ('youtube_video_id', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
